version = 0.1

[dev.deploy.parameters]
region = "eu-west-2"
stack_name = "ticf-integration"
tags = "project=\"di-txma-ticf-integration\" stage=\"dev\""
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides=[
    "Environment=dev",
    "CodeSigningConfigArn=none",
    "PermissionsBoundary=none"
]

[build.validate.parameters]
region = "eu-west-2"
stack_name = "ticf-integration"
parameter_overrides=[
    "Environment=build"
]
