Parameters:
  Environment:
    Description: The environment type
    Type: String
    AllowedValues:
      - dev
      - build
      - staging
      - integration
      - production

Resources:
  SendEmailQueue:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId: '{{resolve:ssm:SqsKmsKeyArn}}'
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SendEmailDeadLetterQueue.Arn
        maxReceiveCount: 5

  SendEmailDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId: '{{resolve:ssm:SqsKmsKeyArn}}'

Outputs:
  SendEmailQueueArn:
    Value: !GetAtt SendEmailQueue.Arn

  SendEmailQueueUrl:
    Value: !Ref SendEmailQueue
